import { describe, expect, it } from 'vitest';

import { checkCommitMessage } from './check.mjs';

const ok = (message: string): void => {
  expect(checkCommitMessage(message)).toEqual({ ok: true, errors: [] });
};

const fails = (message: string, pattern: RegExp): void => {
  const result = checkCommitMessage(message);
  expect(result.ok).toBe(false);
  expect(result.errors.join('\n')).toMatch(pattern);
};

const TRAILER = 'Co-Authored-By: Jane Doe <jane@example.com>';
// A non-breaking space: some clients indent a folded trailer with one.
const NBSP = String.fromCharCode(0xa0);
// Invisible characters must not be able to hide a trailer: a byte order mark, a zero width space.
const BOM = String.fromCharCode(0xfeff);
const ZWSP = String.fromCharCode(0x200b);

describe('conventional commit header', () => {
  it('accepts a plain type and subject', () => ok('feat: add vault indexer'));
  it('accepts a scope', () => ok('fix(core): handle empty frontmatter'));
  it('accepts a breaking-change marker', () => {
    ok('feat!: drop Node 20');
    ok('refactor(api)!: rename endpoints');
  });
  it('accepts a body and footer', () =>
    ok('docs: describe vault format\n\nExplain why files are the source of truth.\n\nRefs: #12'));
  it('accepts a header that starts with a byte order mark', () => ok(`${BOM}feat: add x`));
  it('rejects a header without a type', () => fails('Add stuff', /type/i));
  it('rejects an unknown type', () => fails('feature: add stuff', /type/i));
  it('rejects an uppercase type', () => fails('FEAT: add stuff', /type/i));
  it('rejects an uppercase scope and explains the scope rule', () =>
    fails('feat(Core): add stuff', /scope in lower-case/i));
  it('rejects a missing space after the colon', () => fails('feat:add stuff', /type|subject/i));
  it('rejects an empty subject', () => fails('feat: ', /subject/i));
  it('rejects a header longer than 100 characters', () => fails(`feat: ${'x'.repeat(100)}`, /100/));
  it('counts characters, not UTF-16 code units', () => ok(`feat: ${'🙂'.repeat(90)}`));
  it('rejects an empty message', () => fails('', /empty/i));
  it('rejects a message that only has comments', () =>
    fails('# Please enter the commit message\n#\n', /empty/i));
});

describe('git-generated messages', () => {
  it('accepts merge commits', () => {
    ok("Merge branch 'feature/graph' into main");
    ok("Merge remote-tracking branch 'origin/main'");
    ok('Merge pull request #12 from lokianer/graph');
  });
  it('rejects a hand-written header that merely starts with Merge', () =>
    fails('Merge everything and call it a day', /type/i));
  it('accepts revert commits', () =>
    ok('Revert "feat: add vault indexer"\n\nThis reverts commit 0123456.'));
  it('accepts fixup! and squash! prefixes when the rest is conventional', () => {
    ok('fixup! feat: add vault indexer');
    ok('squash! fix(core): handle empty frontmatter');
    ok('fixup! fixup! feat: add vault indexer');
  });
  it('rejects fixup! of a non-conventional header', () => fails('fixup! Add stuff', /type/i));
});

describe('attribution lines', () => {
  // This project has one author, so no commit credits a second one — whoever or whatever it is.
  it('rejects a co-author trailer', () => fails(`feat: add x\n\n${TRAILER}`, /attribution/i));
  it('rejects a co-author trailer regardless of case', () =>
    fails('feat: add x\n\nco-authored-by: jane doe <jane@example.com>', /attribution/i));
  it('rejects the other keys that claim authorship', () => {
    fails('feat: add x\n\nAssisted-by: Someone <someone@example.com>', /attribution/i);
    fails('feat: add x\n\nGenerated-by: a script', /attribution/i);
    fails('feat: add x\n\nWritten-with: a tool', /attribution/i);
    fails('feat: add x\n\nPair-programmed-with: Someone', /attribution/i);
    fails('feat: add x\n\nOn-behalf-of: Someone <someone@example.com>', /attribution/i);
  });
  it('rejects a "generated with" banner, whatever it credits', () => {
    fails('feat: add x\n\n🤖 Generated with [a tool](https://example.com)', /attribution/i);
    fails('feat: add x\n\nGenerated by a tool', /attribution/i);
    fails('feat: add x\n\nGenerated using a script', /attribution/i);
    fails('feat: add x\n\nGenerated with love', /attribution/i);
  });
  it('accepts a line that quotes the banner rather than being one', () => {
    // A commit that changes this rule has to be able to write the rule down.
    ok('chore: explain the rule\n\n"Generated with …" is refused, and so is a robot emoji.');
  });
  it('rejects a bot signature under any trailer key', () => {
    fails('feat: add x\n\nCo-Authored-By: dependabot[bot] <support@github.com>', /attribution/i);
    fails('feat: add x\n\nSigned-off-by: some-runner[bot] <bot@example.com>', /attribution/i);
  });
  it('rejects a lone robot emoji marker', () => fails('feat: add x 🤖', /attribution/i));
  it('rejects a trailer in the middle of a line or in the header', () => {
    fails(`feat: add x\n\nThanks. ${TRAILER}`, /attribution/i);
    fails(`feat: add x ${TRAILER}`, /attribution/i);
  });
  it('rejects a trailer with whitespace before the colon', () =>
    fails('feat: add x\n\nCo-Authored-By : Jane Doe <jane@example.com>', /attribution/i));
  it('rejects a trailer folded over two lines', () =>
    fails('feat: add x\n\nCo-Authored-By:\n Jane Doe <jane@example.com>', /attribution/i));
  it('rejects indented trailers, as git merge --squash writes them', () => {
    fails(`feat: add x\n\n    ${TRAILER}`, /attribution/i);
    fails(`feat: add x\n\n\t${TRAILER}`, /attribution/i);
    fails(`feat: add x\n\n${NBSP}${TRAILER}`, /attribution/i);
    fails(
      `feat: merge feature\n\nSquashed commit of the following:\n\ncommit 0123456\nAuthor: Jane Doe <jane@example.com>\n\n    feat: inner\n\n    ${TRAILER}`,
      /attribution/i,
    );
  });
  it('rejects attribution hidden behind zero-width characters or a bare CR', () => {
    fails(`feat: add x\n\nCo-Auth${ZWSP}ored-By: Jane Doe <jane@example.com>`, /attribution/i);
    fails(`feat: add x\r${TRAILER}`, /attribution/i);
  });
  it('rejects attribution on a comment line, which git commit -m keeps', () =>
    fails(`feat: add x\n\n# ${TRAILER}`, /attribution/i));

  // Saying who vouches for a change, or who found the problem, is not claiming to have made it.
  it('accepts the trailers that are not about authorship', () => {
    ok('feat: add x\n\nSigned-off-by: Jane Doe <jane@example.com>');
    ok('feat: add x\n\nReviewed-by: Jane Doe <jane@example.com>');
    ok('fix: handle an empty vault\n\nReported-by: Jane Doe <jane@example.com>\nRefs: #12');
  });
  // The hook watches the shape of a trailer, not the language of a sentence: a body explains
  // what was done, and "built with" is ordinary English.
  it('accepts prose that happens to read like a credit', () => {
    ok('fix(core): ignore files generated by the build');
    ok('chore: keep the minimumReleaseAgeExclude lines generated by pnpm');
    ok('feat: regenerate the lockfile generated with pnpm 12');
    ok('feat(editor): restore the selection created by cursor drag');
    ok('feat(web): show the field\n\nImplemented with a state field and one dispatch.');
  });
  it('reports every offending line once', () => {
    const result = checkCommitMessage(`feat: add x\n\n${TRAILER}\nGenerated with a tool`);
    expect(result.ok).toBe(false);
    expect(result.errors).toHaveLength(2);
    expect(result.errors[0]).toMatch(/line 3/);
    expect(result.errors[1]).toMatch(/line 4/);
  });
});

describe('git comment handling', () => {
  it('ignores the standard commit template', () =>
    ok(
      "feat: add x\n# Please enter the commit message for your changes. Lines starting\n# with '#' will be ignored, and an empty message aborts the commit.\n#\n# On branch main\n# Changes to be committed:\n#\tmodified:   README.md\n#",
    ));
  it('ignores everything after the scissors line', () =>
    ok(
      `feat: add x\n# ------------------------ >8 ------------------------\ndiff --git a/x b/x\n+${TRAILER}`,
    ));
  it('ignores a trailing newline and CRLF line endings', () =>
    ok('feat: add x\r\n\r\nBody line.\r\n'));
});
