import { describe, expect, it } from 'vitest';

import { checkCommitMessage } from './check.mjs';

const ok = (message: string): void => {
  expect(checkCommitMessage(message)).toEqual({ ok: true, errors: [] });
};

const fails = (message: string, pattern: RegExp): void => {
  const result = checkCommitMessage(message);
  expect(result.ok).toBe(false);
  expect(result.errors.join('\n')).toMatch(pattern);
};

const CLAUDE_TRAILER = 'Co-Authored-By: Claude <noreply@anthropic.com>';

describe('conventional commit header', () => {
  it('accepts a plain type and subject', () => ok('feat: add vault indexer'));
  it('accepts a scope', () => ok('fix(core): handle empty frontmatter'));
  it('accepts a breaking-change marker', () => {
    ok('feat!: drop Node 20');
    ok('refactor(api)!: rename endpoints');
  });
  it('accepts a body and footer', () =>
    ok('docs: describe vault format\n\nExplain why files are the source of truth.\n\nRefs: #12'));
  it('accepts a header that starts with a byte order mark', () => ok('\uFEFFfeat: add x'));
  it('rejects a header without a type', () => fails('Add stuff', /type/i));
  it('rejects an unknown type', () => fails('feature: add stuff', /type/i));
  it('rejects an uppercase type', () => fails('FEAT: add stuff', /type/i));
  it('rejects an uppercase scope and explains the scope rule', () =>
    fails('feat(Core): add stuff', /scope in lower-case/i));
  it('rejects a missing space after the colon', () => fails('feat:add stuff', /type|subject/i));
  it('rejects an empty subject', () => fails('feat: ', /subject/i));
  it('rejects a header longer than 100 characters', () => fails(`feat: ${'x'.repeat(100)}`, /100/));
  it('counts characters, not UTF-16 code units', () => ok(`feat: ${'🙂'.repeat(90)}`));
  it('rejects an empty message', () => fails('', /empty/i));
  it('rejects a message that only has comments', () =>
    fails('# Please enter the commit message\n#\n', /empty/i));
});

describe('git-generated messages', () => {
  it('accepts merge commits', () => {
    ok("Merge branch 'feature/graph' into main");
    ok("Merge remote-tracking branch 'origin/main'");
    ok('Merge pull request #12 from lokianer/graph');
  });
  it('rejects a hand-written header that merely starts with Merge', () =>
    fails('Merge everything and call it a day', /type/i));
  it('accepts revert commits', () =>
    ok('Revert "feat: add vault indexer"\n\nThis reverts commit 0123456.'));
  it('accepts fixup! and squash! prefixes when the rest is conventional', () => {
    ok('fixup! feat: add vault indexer');
    ok('squash! fix(core): handle empty frontmatter');
    ok('fixup! fixup! feat: add vault indexer');
  });
  it('rejects fixup! of a non-conventional header', () => fails('fixup! Add stuff', /type/i));
});

describe('attribution lines', () => {
  it('rejects a Claude co-author trailer', () =>
    fails(`feat: add x\n\n${CLAUDE_TRAILER}`, /attribution/i));
  it('rejects a co-author trailer regardless of case', () =>
    fails('feat: add x\n\nco-authored-by: Claude Opus 5 <noreply@anthropic.com>', /attribution/i));
  it('rejects the Claude Code banner', () =>
    fails(
      'feat: add x\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)',
      /attribution/i,
    ));
  it('rejects "Generated by" and "Generated using" banners', () => {
    fails('feat: add x\n\nGenerated by GitHub Copilot', /attribution/i);
    fails('feat: add x\n\nGenerated using Claude Code', /attribution/i);
    fails('feat: add x\n\nGenerated with love', /attribution/i);
  });
  it('rejects bot co-author trailers', () =>
    fails('feat: add x\n\nCo-Authored-By: dependabot[bot] <support@github.com>', /attribution/i));
  it('rejects a lone robot emoji marker', () => fails('feat: add x 🤖', /attribution/i));
  it('rejects credit phrasings that name a tool', () => {
    fails('feat: add x\n\nWritten with Claude Code.', /attribution/i);
    fails('feat: add x\n\nImplemented with Claude Code', /attribution/i);
    fails('feat: add x\n\nPair-programmed with Claude', /attribution/i);
    fails('feat: add x\n\nCoded by an AI', /attribution/i);
  });
  it('rejects other trailer keys that name a tool or an AI', () => {
    fails('feat: add x\n\nAssisted-by: Claude <noreply@anthropic.com>', /attribution/i);
    fails('feat: add x\n\nGenerated-by: Claude <noreply@anthropic.com>', /attribution/i);
    fails('feat: add x\n\nSigned-off-by: Claude <noreply@anthropic.com>', /attribution/i);
    fails('feat: add x\n\nCo-Authored-By: AI Assistant <ai@example.com>', /attribution/i);
  });
  it('rejects a trailer in the middle of a line or in the header', () => {
    fails(`feat: add x\n\nThanks. ${CLAUDE_TRAILER}`, /attribution/i);
    fails(`feat: add x ${CLAUDE_TRAILER}`, /attribution/i);
  });
  it('rejects a trailer with whitespace before the colon', () =>
    fails('feat: add x\n\nCo-Authored-By : Claude <noreply@anthropic.com>', /attribution/i));
  it('rejects a trailer folded over two lines', () =>
    fails('feat: add x\n\nCo-Authored-By:\n Claude <noreply@anthropic.com>', /attribution/i));
  it('rejects indented trailers, as git merge --squash writes them', () => {
    fails(`feat: add x\n\n    ${CLAUDE_TRAILER}`, /attribution/i);
    fails(`feat: add x\n\n\t${CLAUDE_TRAILER}`, /attribution/i);
    fails(`feat: add x\n\n\u00A0${CLAUDE_TRAILER}`, /attribution/i);
    fails(
      `feat: merge feature\n\nSquashed commit of the following:\n\ncommit 0123456\nAuthor: Jane Doe <jane@example.com>\n\n    feat: inner\n\n    ${CLAUDE_TRAILER}`,
      /attribution/i,
    );
  });
  it('rejects attribution hidden behind zero-width characters or a bare CR', () => {
    fails('feat: add x\n\nCo-Authored-By: Cl\u200Baude <noreply@anthropic.com>', /attribution/i);
    fails(`feat: add x\r${CLAUDE_TRAILER}`, /attribution/i);
  });
  it('rejects attribution on a comment line, which git commit -m keeps', () =>
    fails(`feat: add x\n\n# ${CLAUDE_TRAILER}`, /attribution/i));
  it('accepts a human co-author trailer', () =>
    ok('feat: add x\n\nCo-Authored-By: Jane Doe <jane@example.com>'));
  it('accepts humans whose names are also tool names', () => {
    ok('feat: add x\n\nCo-Authored-By: Devin Smith <devin@example.com>');
    ok('feat: add x\n\nReviewed-by: Devin Brown <devin@example.com>');
  });
  it('accepts plain mentions of tools that are not credits', () => {
    ok('docs: add CLAUDE.md with the project rules for Claude Code sessions');
    ok('feat: add x\n\nReported by a Copilot user.');
    ok('docs: note that reports from bot scanners are triaged by the maintainer');
  });
  it('accepts ordinary uses of "generated by" and "cursor"', () => {
    ok('fix(core): ignore files generated by the build');
    ok('chore: keep the minimumReleaseAgeExclude lines generated by pnpm');
    ok('feat: regenerate the lockfile generated with pnpm 12');
    ok('feat(editor): restore the selection created by cursor drag');
    ok('feat(editor): move the cursor to the end of the line created by Enter');
  });
  it('accepts the Phase 5 local AI feature wording', () =>
    ok('feat(web): add AI-assisted related-notes panel\n\nSuggestions run locally via Ollama.'));
  it('reports every offending line once', () => {
    const result = checkCommitMessage(
      `feat: add x\n\n${CLAUDE_TRAILER}\nGenerated with Claude Code`,
    );
    expect(result.ok).toBe(false);
    expect(result.errors).toHaveLength(2);
    expect(result.errors[0]).toMatch(/line 3/);
    expect(result.errors[1]).toMatch(/line 4/);
  });
});

describe('git comment handling', () => {
  it('ignores the standard commit template', () =>
    ok(
      "feat: add x\n# Please enter the commit message for your changes. Lines starting\n# with '#' will be ignored, and an empty message aborts the commit.\n#\n# On branch main\n# Changes to be committed:\n#\tmodified:   README.md\n#",
    ));
  it('ignores everything after the scissors line', () =>
    ok(
      `feat: add x\n# ------------------------ >8 ------------------------\ndiff --git a/x b/x\n+${CLAUDE_TRAILER}`,
    ));
  it('ignores a trailing newline and CRLF line endings', () =>
    ok('feat: add x\r\n\r\nBody line.\r\n'));
});
